# Generated by Django 3.2.8 on 2021-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
