# Generated by Django 3.2.8 on 2021-10-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
