# Generated by Django 3.2.8 on 2021-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_value_order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ManyToManyField(related_name='payment_orders', to='api.Order'),
        ),
    ]
